### ISSUE TITLE
Install windup addon.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-operator#14]
The operator needs to install the windup addon.  This includes:

The windup CR in the tackle namespace.
```
---
kind: Addon
apiVersion: tackle.konveyor.io/v1alpha1
metadata:
  name: windup
spec:
  image: quay.io/konveyor/tackle2-addon-windup.
  mounts:
  - claim: m2
    name: m2
```

The claim is RWX and can follow the same pattern as buckets.  The same initial size is fine for now.  We can properly adjust the default before GA.

Related to: https://github.com/konveyor/tackle2-operator/issues/13
