### ISSUE TITLE
Support new "admin" addon.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-operator#53]
Create quay.io/konveyor/tackle2-addon repository.  Trigger builds on konveyor/tackle2-addon (github).

Operator install the CR:
```
---
kind: Addon
apiVersion: tackle.konveyor.io/v1alpha1
metadata:
  name: admin
spec:
  image: quay.io/konveyor/tackle2-addon
  mounts:
  - claim: tackle-windup-addon-volume-claim
    name: m2
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
```

Note: It shares the same ` tackle-windup-addon-volume-claim` as the windup addon.
